[
    "Abu Dhabi",
    "Abuja",
    "Accra",
    "Adamstown",
    "Addis Ababa",
    "Algiers",
    "Amman",
    "Amsterdam",
    "Andorra la Vella",
    "Ankara",
    "Antananarivo",
    "Apia",
    "Ashgabat",
    "Asmara",
    "Astana",
    "Asuncion",
    "Athens",
    "Avarua",
    "Baghdad",
    "Baku",
    "Bamako",
    "Bandar Seri Begawan",
    "Bangkok",
    "Bangui",
    "Banjul",
    "Basseterre",
    "Beijing",
    "Beirut",
    "Belgrade",
    "Belmopan",
    "Berlin",
    "Bern",
    "Bishkek",
    "Bissau",
    "Bloemfontein",
    "Bogota",
    "Brasilia",
    "Bratislava",
    "Brazzaville",
    "Bridgetown",
    "Brussels",
    "Bucharest",
    "Budapest",
    "Buenos Aires",
    "Bujumbura",
    "Cairo",
    "Canberra",
    "Caracas",
    "Castries",
    "Cayenne",
    "Charlotte Amalie",
    "Chisinau",
    "Conakry",
    "Copenhagen",
    "Dakar",
    "Damascus",
    "Dhaka",
    "Dili",
    "Djibouti",
    "Dodoma",
    "Doha",
    "Douglas",
    "Dublin",
    "Dushanbe",
    "Edinburgh of the Seven Seas",
    "El Aaiun",
    "Episkopi Cantonment",
    "Flying Fish Cove",
    "Freetown",
    "Funafuti",
    "Gaborone",
    "Georgetown",
    "Gibraltar",
    "Guatemala City",
    "Gustavia",
    "Hagatna",
    "Hamilton",
    "Hanga Roa",
    "Hanoi",
    "Harare",
    "Havana",
    "Helsinki",
    "Honiara",
    "Islamabad",
    "Jakarta",
    "Jamestown",
    "Jerusalem",
    "Juba",
    "Kabul",
    "Kampala",
    "Kathmandu",
    "Khartoum",
    "Kiev",
    "Kigali",
    "Kingston",
    "Kingstown",
    "Kinshasa",
    "Kuala Lumpur",
    "Kuwait City",
    "Libreville",
    "Lilongwe",
    "Lima",
    "Lisbon",
    "Ljubljana",
    "Lome",
    "London",
    "Luanda",
    "Lusaka",
    "Luxembourg",
    "Madrid",
    "Majuro",
    "Malabo",
    "Male",
    "Mamoudzou",
    "Managua",
    "Manama",
    "Manila",
    "Maputo",
    "Mariehamn",
    "Maseru",
    "Mbabane",
    "Melekeok",
    "Mexico City",
    "Minsk",
    "Mogadishu",
    "Monaco",
    "Monrovia",
    "Montevideo",
    "Moroni",
    "Moscow",
    "Muscat",
    "Nairobi",
    "Nassau",
    "Naypyidaw",
    "New Delhi",
    "New York",
    "Niamey",
    "Nicosia",
    "Nouakchott",
    "Nukualofa",
    "Nuuk",
    "Oranjestad",
    "Oslo",
    "Ottawa",
    "Ouagadougou",
    "Pago Pago",
    "Palikir",
    "Panama City",
    "Papeete",
    "Paramaribo",
    "Paris",
    "Philipsburg",
    "Phnom Penh",
    "Pitcairn",
    "Port Louis",
    "Port Moresby",
    "Port Vila",
    "Port-au-Prince",
    "Port of Spain",
    "Porto-Novo",
    "Prague",
    "Praia",
    "Pretoria",
    "Pristina",
    "Pyongyang",
    "Quito",
    "Rabat",
    "Reykjavik",
    "Riga",
    "Riyadh",
    "Road Town",
    "Rome",
    "Roseau",
    "Saint Helier",
    "Saint John's",
    "Saint Peter Port",
    "Saint-Denis",
    "San Jose",
    "San Juan",
    "San Marino",
    "San Salvador",
    "Sana'a",
    "Santiago",
    "Santo Domingo",
    "Sao Tome",
    "Sarajevo",
    "Seoul",
    "Singapore",
    "Skopje",
    "Sofia",
    "South Tarawa",
    "Sri Jayawardenepura Kotte",
    "St. George's",
    "St. John's",
    "St. Louis",
    "St. Paul's",
    "St. Petersburg",
    "Stockholm",
    "Sucre",
    "Suva",
    "Taipei",
    "Tallinn",
    "Tarawa",
    "Tashkent",
    "Tbilisi",
    "Tegucigalpa",
    "Tehran",
    "Thimphu",
    "Tirana",
    "Tiraspol",
    "Tokyo",
    "Torshavn",
    "Tripoli",
    "Tskhinvali",
    "Tunis",
    "Ulaanbaatar",
    "Unnuakot",
    "Vaduz",
    "Valletta",
    "The Valley",
    "Victoria",
    "Vienna",
    "Vientiane",
    "Vilnius",
    "Warsaw",
    "Washington D.C.",
    "Wellington",
    "West Island",
    "Willemstad",
    "Windhoek",
    "Yamoussoukro",
    "Yaounde",
    "Yerevan",
    "Zagreb",
    "Zurich"
]